name: Bug checker

on:
  schedule:
    - cron: '0 16 14 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check bug templates
        run: |
          python checker.py
          echo "CURRENT_DATE=$(date '+%Y-%m-%d UTC')" >> $GITHUB_ENV
      - name: Commit & Push
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: "Update ${{env.CURRENT_DATE}}"
