name: Bug checker

on:
  schedule:
    - cron: '0 16 * * 6'
  workflow_dispatch:

jobs:
  condition:
    runs-on: ubuntu-latest
    outputs:
      pass: ${{ steps.check.outputs.pass }}
    steps:
      - name: Day of the month
        id: check
        run: |
          day=$(date +%-d)
          pass=0
          echo "Today is Day $day of the month."
          if [[ $day > 7 && $day < 15 ]]; then
            pass=1
          elif [[ ${{ github.event_name }} == workflow_dispatch ]]; then
            pass=2
          fi
          echo "pass=$pass" >> $GITHUB_OUTPUT

  checker:
    runs-on: ubuntu-latest
    needs: condition
    if: needs.condition.outputs.pass != 0
    env:
      BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
      OWNER_PASSWORD: ${{ secrets.OWNER_PASSWORD }}
      SDJIRA_EMAIL: ${{ secrets.SDJIRA_EMAIL }}
      SDJIRA_PASSWORD: ${{ secrets.SDJIRA_PASSWORD }}
    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check bug templates
        run: |
          python checker.py
          echo "CURRENT_DATE=$(date '+%Y-%m-%d UTC')" >> $GITHUB_ENV
      - name: Commit & Push
        uses: EndBug/add-and-commit@main
        with:
          default_author: github_actions
          message: "Update ${{env.CURRENT_DATE}}"
